### ISSUE TITLE
new module: camunda-commons-testing

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-commons#4]
I need a lot of test-dependency management (junit, hamcrest, mockito, assertj, needle) in each of my camunda projects.
It would be nice to have a common test project that bundles what we suppose to be "best practice testing".

**Comment by menski** [comment]
Hi Jan,

I will close this issue as the corresponding pull request #6 was also closed.

Cheers,
Sebastian

**Comment by jangalinski** [comment]
+1
